apiVersion: v1
kind: Service
metadata:
  name: fraud-api-service
spec:
  selector:
    app: fraud-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort   # Change to LoadBalancer if deploying to cloud
